[colors]
foreground = "#dddddd"
background = "#000000"
cursor_bg = "#fffacd"
cursor_fg = "#000000"
cursor_border = "#fffacd"
selection_fg = "#000000"
selection_bg = "#fffacd"


ansi = ["#000000", "#cc0403", "#19cb00", "#cecb00", "#0d73cc", "#cb1ed1", "#0dcdcd", "#dddddd"]
brights = ["#767676", "#f2201f", "#23fd00", "#fffd00", "#1a8fff", "#fd28ff", "#14ffff", "#ffffff"]
