#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
~/.scripts/monitors.sh

pidof dunst && killall dunst 
pidof pulseadio && killall pulseaudio

wal -i ~/.config/bspwm/wallpapers/mountain-road-car-lights.jpg -n
dunst &
pulseaudio &
.config/polybar/launch.sh
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --bg-scale ~/.config/bspwm/wallpapers/mountain-road-car-lights.jpg
picom --respect-prop-shadow &


bspc config border_width         2
bspc config window_gap           50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color $(xrdb -query | grep "*color4" | grep "#[0-9A-Za-z]\+" -o)
bspc config normal_border_color $(xrdb -query | grep "*color0" | grep "#[0-9A-Za-z]\+" -o)

# bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

xsetroot -cursor_name left_ptr &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

notify-send "Hello old friend!"
