#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

sh ~/MAIN/scripts/autostart.sh

# MONITORS #
hc detect_monitors

sh ~/.config/herbstluftwm/keybindings
sh ~/.config/herbstluftwm/settings
sh ~/.config/herbstluftwm/rules

# unlock, just to be sure
hc unlock

killall polybar
exconman set polybar.pin_workspaces "false"
python ~/MAIN/scripts/launch_polybars.py &
