#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

#hc emit_hook reload

sh $DOTFILES_BRAIN_ROOT/scripts/autostart.sh

# MONITORS #
hc detect_monitors

sh ~/.config/herbstluftwm/keybindings
sh ~/.config/herbstluftwm/settings
sh ~/.config/herbstluftwm/rules

# unlock, just to be sure
hc unlock

killall polybar
exconman set polybar.pin_workspaces "false"
python $DOTFILES_BRAIN_ROOT/scripts/launch_polybars.py &
