#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

# SETTINGS #
hc set window_gap '10'
hc set smart_window_surroundings off
hc set mouse_recenter_gap 0
hc set hide_covered_windows on
hc set tree_style '╾│ ├└╼─┐'
hc set auto_detect_monitors on
hc set focus_stealing_prevention false

# FRAME #
hc set default_frame_layout 'grid'
hc set frame_border_width '0'
hc set frame_bg_transparent 'on'
hc set frame_transparent_width 0
hc set frame_gap '0'
hc set always_show_frame on
hc set smart_frame_surroundings off
hc set frame_padding 0
hc set frame_border_normal_color '#353b45'
hc set frame_border_active_color '#98c379'
hc set frame_bg_normal_color '#282c3480'
hc set frame_bg_active_color '#282c3480'

# ATTRS #
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.title_height 0
hc attr theme.inner_width '0'
hc attr theme.outer_width '0'
hc attr theme.padding_top 0
hc attr theme.padding_right 0
hc attr theme.padding_bottom 0
hc attr theme.padding_left '0'
hc attr theme.border_width '2'
hc attr theme.title_font 'Dina:size=10'

# COLORS #
hc attr theme.normal.title_color '#abb2bf'
hc attr theme.active.title_color '#353b45'
hc attr theme.active.color '#abb2bf'
hc attr theme.normal.color '#353b45'
hc attr theme.urgent.color '#d19a66'
hc attr theme.inner_color '#353b45'
hc attr theme.inner_width '0'
hc attr theme.outer_color '#353b45'
hc attr theme.outer_width '0'
hc attr theme.background_color '#282c34'
