#!/bin/sh

sxhkd &

# Setup monitors
autorandr --change

# Manage desktops
python ~/.config/scrypts/bspwm_manage_desktops.py

# Kill programs before starting them (if they were open)
pidof dunst && killall dunst

bspc config top_padding 0
bspc config bottom_padding 0
bspc config border_width 3
bspc config window_gap 15
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config automatic_scheme alternate

bspc config normal_border_color "#242924"
bspc config focused_border_color "#87711d"
bspc config active_border_color "#809980"
bspc config urgent_border_color "#e6193c"
bspc config presel_feedback_color "#87711d"

# 3rd party
dunst &
python .config/polybar/launch.py &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --no-fehbg --bg-fill /home/breton/Pictures/wallpapers/generated.png &
pidof picom || picom --experimental-backends &

# Take a break reminder
ps -fA | grep python | grep ~/.config/scrypts/break_notifier.py || python ~/.config/scrypts/break_notifier.py &
# Night mode
python ~/.config/scrypts/night_mode/main.py no_toggle

# Reload termite configs
killall -USR1 termite

# Set cursor to pointer
xsetroot -cursor_name left_ptr &
# Keyboard delay and rate
xset r rate 250 30

notify-send "Started BSPWM using `audot query config modifier`"
