#!/usr/bin/env zsh

sxhkd &
python ~/.config/scripts/monitors_setup.py

# Kill programs before starting them (if they were open)
pidof picom && killall picom
pidof dunst && killall dunst

# Notifications
dunst &
# Status bar(s)
.config/polybar/launch.sh &
# Polkit
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --no-fehbg --bg-fill <>|wallpaper|<> &
# Compositor
picom --experimental-backends &

bspc config border_width         <>|border_width|<>
bspc config window_gap           <>|window_gap|<>

bspc config split_ratio          0.50
bspc config borderless_monocle   <>|borderless_monocle|<>
bspc config gapless_monocle      <>|gapless_monocle|<>

bspc config automatic_scheme alternate

bspc config normal_border_color "<>|normal_border_color|<>"
bspc config focused_border_color "<>|focused_border_color|<>"
bspc config active_border_color "<>|active_border_color|<>"

xsetroot -cursor_name left_ptr &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Org.gnome.Nautilus desktop='^4' follow=on focus=on
bspc rule -a Code desktop='^2' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

notify-send "From $(uname -n)" "Hey $(whoami)!\nLet's get the show on the road!"