#! /bin/sh

sxhkd &


# MONITORS
~/.scripts/monitors.sh
#xrandr --output VGA-1 --primary --auto --left-of eDP-1
#bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0

# AUTOSTART
feh --bg-scale ~/Desktop/Other/Wallpapers/abstract-art-black-background-blur-1040499.jpg
pulseaudio --kill
pulseaudio --start
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh

# GLOBAL SETTINGS
bspc config border_width        2
bspc config window_gap          15
bspc config focused_border_color  "#558899"
bspc config normal_border_color   "#444444"

bspc config automatic_scheme alternate 
bspc config initial_polarity second_child
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier super
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off




