#!/bin/sh

sxhkd &

autorandr --change

# Manage desktops
python ~/.config/scrypts/bspwm_manage_desktops.py

# Kill programs before starting them (if they were open)
pidof picom && killall picom
pidof dunst && killall dunst

bspc config top_padding 0
bspc config bottom_padding 0
bspc config border_width 2
bspc config window_gap 25
bspc config split_ratio          0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config automatic_scheme alternate

bspc config normal_border_color "#0c060d"
bspc config focused_border_color "#A04FA4"
bspc config active_border_color "#7d8193"
bspc config urgent_border_color "#E82791"
bspc config presel_feedback_color "#84a9c6"

# 3rd party
dunst &
python .config/polybar/launch.py &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
feh --no-fehbg --bg-fill /home/breton/Pictures/wallpapers/purplecity.jpg &
picom --experimental-backends &

# Night mode
python ~/.config/scrypts/night_mode no_toggle

# Reload termite configs
killall -USR1 termite

# Set cursor to pointer
xsetroot -cursor_name left_ptr &

notify-send "BSPWM" "Started/Restarted bspwm"
