#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

# remove all existing keybindings
hc keyunbind --all


# keybindings
Mod=Mod4
Alt=Mod1

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-e spawn autorandr --change
hc keybind $Mod-w close
hc keybind $Mod-Return spawn sh -c "WXINIT_X11_SCALE_FACTOR=1 ${TERMINAL:-xterm}"

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-e split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-q remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-d   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-i jumpto urgent

# custom
hc keybind "$Mod-Insert" spawn python $DOT_ROOT/scripts/gui/keyboard_layout.py
hc keybind $Mod-c spawn python $DOT_ROOT/scripts/gui/commander.py
hc keybind $Mod-a spawn rofi -modi drun -show drun
hc keybind $Alt-a spawn rofi -modi window -show window

# Volume
hc keybind XF86AudioLowerVolume spawn pulseaudio-ctl down
hc keybind XF86AudioRaiseVolume spawn pulseaudio-ctl up
hc keybind XF86AudioMute spawn pulseaudio-ctl mute

# Scrots
hc keybind $Mod-F12 scrot '%Y-%m-%d_$wx$h_scrot.png' -e 'mv $f ~/screenshots'

# Brightness
hc keybind $Mod-XF86AudioRaiseVolume spawn brightnessctl s 10%+
hc keybind $Mod-XF86AudioLowerVolume spawn brightnessctl s 10%-

# Sleep
hc keybind $Mod-Escape spawn systemctl suspend

# Set random wallpaper
hc keybind $Mod-r spawn sh $DOT_ROOT/scripts/set_random_wallpaper.sh

# Notifications
hc keybind Control-Shift-period spawn dunstctl context
hc keybind Control-Shift-space spawn dunstctl close-all
hc keybind Control-space spawn dunstctl close
hc keybind Control-Shift-grave spawn dunstctl history-pop
