[colors]
foreground = "#1a212b"
background = "#e3e0dd"
cursor_bg = "#1a212b"
cursor_fg = "#e3e0dd"
cursor_border = "#1a212b"
selection_fg = "#e3e0dd"
selection_bg = "#e3e0dd"

ansi = ["#e3e0dd","#465f3d","#305c80","#7b4d43","#485a71","#963e0c","#4e637a","#1a212b"]
brights = ["#6a6d72","#465c66","#bbb9b9","#929395","#42474e","#161c24","#3b5b80","#12171e"]

