[colors]
foreground = "#a6accd"
background = "#0f111a"
cursor_bg = "#a6accd"
cursor_fg = "#0f111a"
cursor_border = "#a6accd"
selection_fg = "#0f111a"
selection_bg = "#0f111a"

ansi = ["#0f111a","#f78c6c","#c3e88d","#c792ea","#82aaff","#c792ea","#f07178","#a6accd"]
brights = ["#464b5d","#f78c6c","#1a1c25","#1f2233","#84ffff","#a6accd","#ffcb6b","#a6accd"]

