[colors]
foreground = "#ccceb8"
background = "#232729"
cursor_bg = "#ccceb8"
cursor_fg = "#232729"
cursor_border = "#ccceb8"
selection_fg = "#232729"
selection_bg = "#232729"

ansi = ["#232729","#507ca7","#e7ba39","#a58785","#b65d71","#9d6c64","#84949e","#ccceb8"]
brights = ["#888b7f","#d0d3b2","#454846","#676a62","#aaac9c","#d3d5c3","#e3ac6d","#dbdccd"]

