[colors]
foreground = "#cbcbcb"
background = "#17292d"
cursor_bg = "#cbcbcb"
cursor_fg = "#17292d"
cursor_border = "#cbcbcb"
selection_fg = "#17292d"
selection_bg = "#17292d"

ansi = ["#17292d","#847575","#4f844f","#8e7365","#787878","#787878","#527f88","#cbcbcb"]
brights = ["#838a8c","#647f64","#3b494c","#5f6a6c","#a7abab","#d3d3d3","#787878","#dadada"]

