#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

#hc emit_hook reload

# AUTOSTART
# Notification daemon
killall dunst

# X settings
xset r rate 250 30 
xsetroot -cursor_name left_ptr
setxkbmap -option keypad:pointerkeys
setxkbmap -option caps:backspace
xset r 66 # Enable repeat for capslock key
xkbset ma 1 5 70 6 0
xkbset exp 60 =mousekeys

# Enable nightmode if it was enabled prior to restarting
restore_nightmode_state

# Wallpaper
sh $XDG_DATA_HOME/dotfiles/wallpaper

# MONITORS
hc detect_monitors

# Source other files
sh ~/.config/herbstluftwm/keybindings
sh ~/.config/herbstluftwm/settings
sh ~/.config/herbstluftwm/rules

# Reload systemd units
systemctl --user restart picom
systemctl --user restart polybar
systemctl --user restart polkit_gui

# Setup monitors if it is the first time this config is running since starting X server
if [[ -f "$XDG_DATA_HOME/herbstluftwm/first_start.txt" ]]; then
	rm "$XDG_DATA_HOME/herbstluftwm/first_start.txt"
	autorandr --change
fi

# Check if dots repo is up to date with remote
pushd $DOT_ROOT
git remote update

status=$(git status -uno)
if [[ $(echo $status | grep -w "is up to date") ]]; then
	notify-send "Local and remote are equal" -a "dots"
elif [[ $(echo $status | grep -w "is ahead of") ]]; then
	notify-send "Local is ahead of remote, please push commits" -a "dots"
else
	notify-send "Remote is ahead of local, please pull commits" -a "dots"
fi
popd

# unlock, just to be sure
hc unlock
