#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

#hc emit_hook reload

# AUTOSTART
# Notification daemon
killall dunst

# Polkit
sh ~/.config/herbstluftwm/polkit

# X settings
xset r rate 250 30 
xsetroot -cursor_name left_ptr
setxkbmap -option keypad:pointerkeys
setxkbmap -option caps:backspace
xset r 66 # Enable repeat for capslock key
xkbset ma 1 5 70 6 0
xkbset exp 60 =mousekeys

# Enable nightmode if it was enabled prior to restarting
python $DOT_ROOT/scripts/night_mode.py

# Wallpaper
sh $XDG_DATA_HOME/dotfiles/wallpaper

# MONITORS
hc detect_monitors

# Source other files
sh ~/.config/herbstluftwm/keybindings
sh ~/.config/herbstluftwm/settings
sh ~/.config/herbstluftwm/rules

# Reload systemd units
systemctl --user restart picom
systemctl --user restart polybar
systemctl --user restart polkit_gui

# Setup monitors if it is the first time this config is running since starting X server
if [[ -f "$XDG_DATA_HOME/herbstluftwm/first_start.txt" ]]; then
	rm "$XDG_DATA_HOME/herbstluftwm/first_start.txt"
	autorandr --change
fi

# Start health script if not already running
pgrep -f "sh $DOT_ROOT/scripts/polybar/health.sh" || sh $DOT_ROOT/scripts/polybar/health.sh &

# Reload wezterm (in a very hacky manner, refer to wezterm.nix)
if [[ ! -f $XDG_DATA_HOME/wezterm/reload.txt ]]; then
	mkdir $XDG_DATA_HOME/wezterm
	touch reload.txt
fi

if [[ $(cat $XDG_DATA_HOME/wezterm/reload.txt) == "r" ]]; then
	truncate -s-1 $XDG_DATA_HOME/wezterm/reload.txt
else
	echo "r" >> $XDG_DATA_HOME/wezterm/reload.txt
fi

# Check if dots repo is up to date with remote
pushd $DOT_ROOT
git remote update

status=$(git status -uno) 
if [[ $(echo $status | grep -w "is up to date") ]]; then
	notify-send "Configuration is up to date with remote" -a ""
elif [[ $(echo $status | grep -w "is ahead of") ]]; then
	notify-send "Configuration is ahead of remote" -a ""
else
	notify-send "Configuration is behind remote" -a ""
fi
popd

# unlock, just to be sure
hc unlock
