#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

get_setting() {
	#echo $(cat $XDG_DATA_HOME/herbstluftwm/settings.json | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' | grep "$1=" | sed "s/$1=//g")
	echo $(cat $XDG_DATA_HOME/herbstluftwm/settings.json | jq -r ".$1")
}

# SETTINGS #
hc set auto_detect_monitors on
hc set focus_stealing_prevention false
hc set hide_covered_windows on
hc set mouse_recenter_gap 0
hc set smart_window_surroundings off
hc set tree_style '╾│ ├└╼─┐'
hc set window_gap $(get_setting "window_gap")

# FRAME #
hc set always_show_frame on
hc set default_frame_layout 'grid'
hc set frame_bg_active_color '#1d2021'
hc set frame_bg_normal_color '#1d2021'
hc set frame_bg_transparent 'on'
hc set frame_border_active_color '#928374'
hc set frame_border_normal_color '#282828'
hc set frame_border_width '0'
hc set frame_gap '0'
hc set frame_padding 0
hc set frame_transparent_width 0
hc set smart_frame_surroundings off

# RESET #
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# ATTRS #
hc attr theme.border_width $(get_setting "border_width")
hc attr theme.inner_width "$(get_setting "inner_width")"
hc attr theme.outer_width $(get_setting "outer_width")
hc attr theme.padding_bottom $(get_setting "padding_bottom")
hc attr theme.padding_left $(get_setting "padding_left")
hc attr theme.padding_right $(get_setting "padding_right")
hc attr theme.padding_top $(get_setting "padding_top")
hc attr theme.title_align $(get_setting "title_align")
hc attr theme.title_depth $(get_setting "title_depth")
hc attr theme.title_font "$(get_setting "title_font")"
hc attr theme.title_height $(get_setting "title_height")


# COLORS #
hc attr theme.background_color '#1d2021'
hc attr theme.active.color $(get_setting "active_color")
hc attr theme.active.inner_color "$(get_setting "active_inner_color")"
hc attr theme.active.outer_color "$(get_setting "active_outer_color")"
hc attr theme.active.title_color "$(get_setting "active_title_color")"
hc attr theme.active.tab_color $(get_setting "active_tab_color")
hc attr theme.active.tab_inner_color $(get_setting "active_tab_inner_color")
hc attr theme.active.tab_outer_color $(get_setting "active_tab_outer_color")
hc attr theme.active.tab_title_color $(get_setting "active_tab_title_color")
hc attr theme.normal.color $(get_setting "normal_color")
hc attr theme.normal.inner_color "$(get_setting "normal_inner_color")"
hc attr theme.normal.outer_color "$(get_setting "normal_outer_color")"
hc attr theme.normal.tab_color $(get_setting "normal_tab_color")
hc attr theme.normal.tab_inner_color $(get_setting "normal_tab_inner_color")
hc attr theme.normal.tab_outer_color $(get_setting "normal_tab_outer_color")
hc attr theme.normal.tab_title_color $(get_setting "normal_tab_title_color")
hc attr theme.normal.title_color "$(get_setting "normal_title_color")"
hc attr theme.urgent.color $(get_setting "urgent_color")
hc attr theme.urgent.inner_color "$(get_setting "urgent_inner_color")"
hc attr theme.urgent.outer_color "$(get_setting "urgent_outer_color")"
